[package]
name = "uninstall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
resolve-path = "0.1.0"
rust_search = "2.1.0"
regex = "1.10.4"

